AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  DBName:
    Type: String
    Description: The name of the database
    Default: MyMySQLDB

  MasterUsername:
    Type: String
    Description: The master username for the database
    Default: admin

  MasterUserPassword:
    Type: String
    NoEcho: true
    Description: The master user password for the database
    Default: MySecurePassword123

  DBInstanceIdentifier:
    Type: String
    Description: The identifier for the Aurora DB instance
    Default: MyMySQLDBInstance

  ProxyName:
    Type: String
    Description: The name for the Aurora Database Proxy
    Default: MyMySQLDBProxy

  SecretReaderRoleArn:
    Type: String
    Default: arn:aws:iam::137026196014:role/aws-service-role/rds.amazonaws.com/AWSServiceRoleForRDS

  ProxySecretArn:
    Type: String
    Default: arn:aws:secretsmanager:ap-northeast-1:137026196014:secret:MySecretForMySQLDBProxy-BX1XSU

  SubnetIds:
    Type: String
    Default: subnet-077b1c87b03d9fc4f,subnet-0df0d9dd885aa6e86,subnet-093f7d804559ba283

  SecurityGroup:
    Type: String
    Default: sg-03356b93c8c5f453d

Resources:
  MySQLDB:
    Type: AWS::RDS::DBInstance
    DeletionPolicy: Delete
    Properties:
      Engine: mysql
      DBInstanceIdentifier: !Ref DBInstanceIdentifier
      MasterUsername: !Ref MasterUsername
      MasterUserPassword: !Ref MasterUserPassword
      AllocatedStorage: 5
      DBInstanceClass: db.t3.micro # Smallest and least expensive instance class
      BackupRetentionPeriod: 0
      MultiAZ: false # For cost-saving in a testing environment
      Port: 3306
      VPCSecurityGroups:
        - !Ref SecurityGroup

  MySQLDBProxy:
    Type: "AWS::RDS::DBProxy"
    DeletionPolicy: Delete
    Properties:
      DBProxyName: !Ref ProxyName
      EngineFamily: "MYSQL"
      RoleArn: !Ref SecretReaderRoleArn
      Auth:
        - {
            AuthScheme: SECRETS,
            SecretArn: !Ref ProxySecretArn,
            IAMAuth: DISABLED,
          }
      VpcSubnetIds:
        Fn::Split: [",", !Ref SubnetIds]

Outputs:
  MySQLDBEndpoint:
    Description: "Aurora Database Endpoint"
    Value: !GetAtt MySQLDB.Endpoint.Address

  MySQLDBProxyEndpoint:
    Description: "Aurora Database Proxy Endpoint"
    Value: !GetAtt MySQLDBProxy.Endpoint
